build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.2
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      environment:
        php:
          version: 7.2
        hosts:
          dev.local: '127.0.0.1'
        apache2:
          modules: ['rewrite']
          sites:
            ubiquity:
              host: 'dev.local'
              web_root: 'web/'
        selenium: true
      services:
          mysql: 5.7
      tests:
        before:
          - (cd web/ && composer update -a)
          - sudo cp web/tests/files/xdebug.ini /home/scrutinizer/.phpenv/versions/7.2.13/etc/conf.d/xdebug.ini
          - mysql -u root mysql < web/tests/unit/db/messagerie.sql
          - ./web/vendor/bin/Ubiquity init-cache
          - sudo chmod 777 -R web/ && sudo chown -R www-data:www-data web/
          - sudo service apache2 restart && sudo service apache2 reload 
          - sudo curl -v http://dev.local/

        override:
          - command: (cd web/ && ./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml)
            coverage:
              file: web/tests/_output/coverage.xml
              format: clover
checks:
    php:
        code_rating: true
filter:
    paths: ["web/vendor/phpmv/ubiquity/Ubiquity/"]
    excluded_paths:
        - web/vendor/phpmv/ubiquity/Ubiquity/log/
        - web/vendor/phpmv/ubiquity/Ubiquity/controllers/Autoloader.php
        - web/vendor/phpmv/ubiquity/Ubiquity/controllers/admin/
        - web/vendor/phpmv/ubiquity/Ubiquity/annotations/
        - web/vendor/phpmv/ubiquity/Ubiquity/cache/
        - web/vendor/phpmv/ubiquity/Ubiquity/js/Jquery.php
        - web/vendor/phpmv/ubiquity/Ubiquity/utils/git/UGitRepository.php